--[[
  @author Ilias-Timon Poulakis (FeedTheCat)
  @license MIT
  @version 1.0.0
  @about Bundle with all possible configurations of MeMagic
  @metapackage
  @provides
    [main=midi_editor] Generated/FTC_MeMagic (1-2) Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-3) Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-4) Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-5) Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-6) Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-7) Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-8) Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-9) Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-10) Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-11) Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (1-12) Vertically scroll to center of notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-1) Horizontally zoom to item.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-2) Horizontally zoom to item | Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-3) Horizontally zoom to item | Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-4) Horizontally zoom to item | Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-5) Horizontally zoom to item | Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-6) Horizontally zoom to item | Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-7) Horizontally zoom to item | Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-8) Horizontally zoom to item | Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-9) Horizontally zoom to item | Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-10) Horizontally zoom to item | Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-11) Horizontally zoom to item | Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (2-12) Horizontally zoom to item | Vertically scroll to center of notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-1) Horizontally zoom to 4 measures at mouse or edit cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-2) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-3) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-4) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-5) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-6) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-7) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-8) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-9) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-10) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-11) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (3-12) Horizontally zoom to 4 measures at mouse or edit cursor | Vertically scroll to center of notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-1) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-2) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-3) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-4) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-5) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-6) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-7) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-8) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-9) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-10) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-11) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (4-12) Horizontally zoom to 4 measures at at mouse or edit cursor, restrict to item | Vertically scroll to center of notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-1) Horizontally smart zoom to 10 notes at mouse or edit cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-2) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-3) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-4) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-5) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-6) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-7) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-8) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-9) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-10) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-11) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (5-12) Horizontally smart zoom to 10 notes at mouse or edit cursor | Vertically scroll to center of notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-1) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-2) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-3) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-4) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-5) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-6) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-7) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-8) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-9) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-10) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-11) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (6-12) Horizontally smart zoom to 10 notes at mouse or edit cursor, restrict to item | Vertically scroll to center of notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-1) Horizontally scroll to mouse or edit cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-2) Horizontally scroll to mouse or edit cursor | Vertically zoom to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-3) Horizontally scroll to mouse or edit cursor | Vertically zoom to all notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-4) Horizontally scroll to mouse or edit cursor | Vertically scroll to note row under mouse cursor.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-5) Horizontally scroll to mouse or edit cursor | Vertically scroll to note row under mouse cursor, restrict to notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-6) Horizontally scroll to mouse or edit cursor | Vertically scroll to note row under mouse cursor, restrict to notes in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-7) Horizontally scroll to mouse or edit cursor | Vertically scroll to lowest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-8) Horizontally scroll to mouse or edit cursor | Vertically scroll to lowest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-9) Horizontally scroll to mouse or edit cursor | Vertically scroll to highest note in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-10) Horizontally scroll to mouse or edit cursor | Vertically scroll to highest note in item.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-11) Horizontally scroll to mouse or edit cursor | Vertically scroll to center of notes in visible area.lua
    [main=midi_editor] Generated/FTC_MeMagic (7-12) Horizontally scroll to mouse or edit cursor | Vertically scroll to center of notes in item.lua
]]
